### ISSUE TITLE
Pre-release uB0 channel/Firefox support?

### ISSUE THREAD

**Issue by Vangelis66** [JustOff/ublock0-updater#1]
(This is not an issue report as such, rather a request for additional functionality; sincere apologies if this isn't the proper place to ask, but I already have an existing GitHub account... )

 A million thanks for your code and this PM extension; happily using PM 27.5.0a1 on Windows Vista SP2 32bit, uBlock Origin (legacy) is my ad blocker of choice on all my browsers in this laptop.  

 Prior to this add-on, I would use the manual method of updating uB0 (non-webext) directly from GitHub, but I would also choose to install the pre-release builds, too... 

Kindly consider implementing, if at all possible, these two suggestions of mine: 
1. In its current form, this add-on only allows for updating to the latest stable release (e.g. I was on **1.14.9b1** and was successfully updated to **1.14.10**, but not to latest pre-release **1.14.11b0**). 
I realise many PM+uB0 users may choose to shy away from betas/RCs, but could you consider adding support for those, preferably via an add-on selectable option, for the most "adventurous" of us?
2. In its inception, this was created for PM 27.* , but I see latest update implemented support for Seamonkey 2.40+; will you consider also adding support for Firefox 24.* - 56.* ? 
On Windows XP/Vista, highest version of Fx that would run is 52.0.2 (release channel)/52.x.x (ESR channel).
According to [#2612](https://github.com/gorhill/uBlock/issues/2612), Firefox support for the legacy version of uB0 starts from v24 (and obviously will end with v56), however because of [#3013](https://github.com/gorhill/uBlock/issues/3013), Fx 24.* - 51.* will forever stay put at uB0 v1.13.8, while Fx 52.* - 56.* will get from AMO the webext flavour 1.14.+... While PM is now my main browser, I do keep some older versions of Fx (for various tests) plus the latest supported ESR 52.3.0 and I prefer to have the legacy uB0 installed in these... 
For the record, I did some tests locally and your code does work OK with Fx 52.* , however (probably because PM 27.* is forked from Fx ESR 38 codebase), the installed add-on did nothing on Fx ESR 24.8.1; I suspect your add-on uses updated JS code, not compatible with that older Fx version (which, however, is still supported by uB0 legacy...). 

 I fully understand that this extension will lose its practical significance if/when Raymond Hill stops developing/updating the legacy version of uB0, until that time it'd be super to have it working across PM + Fx alike... 

Please accept my gratitude for all your offerings and support to the PM community :1st_place_medal: 
Kind regards

**Comment by JustOff** [comment]
Resolved by [release 1.1.0](https://github.com/JustOff/ublock0-updater/releases/tag/1.1.0).

**Comment by gorhill** [comment]
@JustOff

Just dropping to say thanks for doing this, this is useful to a lot people out there.

**Comment by JustOff** [comment]
@gorhill 
Thank you for your outstanding blocker and continuous support of the entire range of xul-based applications and especially Pale Moon!

**Comment by Vangelis66** [comment]
@JustOff 

Wow; I'm in awe :+1: ; both my suggestions were implemented, and so quickly!!!
Some follow-up: 
1. I tried to install (v1.1.0 in fact) from [APO](https://addons.palemoon.org/addon/ublock0-updater/) on Firefox Nightly 53.0a1 (buildID=20161117030212) and it refused to install; same thing when trying to install v1.1.0 directly from GitHub: 

![v1 1 0-fx53 0a1](https://user-images.githubusercontent.com/9669492/30500581-a492bfc8-9a67-11e7-82b1-5106cb1e628f.jpg)

However, newer v**1.1.1** (currently only on GitHub repo) did install successfully; any explanation why? 

2. For others who did not bother looking at the [code](https://github.com/JustOff/ublock0-updater/commit/c2544df9824cf4f48425bcae66bd242600c86667), Firefox support is for versions **45.0** - **56.*** (and it's an unsigned extension), which means, as per my OP, that Firefox versions **24.*** - **45.0b** will remain unsupported; don't get me wrong, I am not complaining in the slightest, but for completeness can you please clarify whether it was indeed impossible to cover those earlier Fx versions or whether in fact code adaptation would've allowed for that but you opted not to? 

Again, extremely appreciative! 

> Thank you for your outstanding blocker and continuous support 
> of the entire range of xul-based applications and especially Pale Moon! 

Ditto! :+1:

**Comment by Vangelis66** [comment]
I wrote: 

> I tried to install (v1.1.0 in fact) from [APO](https://addons.palemoon.org/addon/ublock0-updater/) on Firefox Nightly 53.0a1 (buildID=20161117030212) and it refused to install; same thing when trying to install v1.1.0 directly from GitHub:
> (snip)
> However, newer v1.1.1 (currently only on GitHub repo) did install successfully; any explanation why?

Case solved; it appears that the .XPI file of version 1.1.0 uploaded to [APO](https://addons.palemoon.org/addon/ublock0-updater/) as well as [GitHub](https://github.com/JustOff/ublock0-updater/releases/tag/1.1.0) has a faulty **install.rdf** file inside, which lacks the Firefox GUID: 
```JS
<?xml version='1.0' encoding='utf-8'?>
<RDF xmlns="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:em="http://www.mozilla.org/2004/em-rdf#">
  <Description about="urn:mozilla:install-manifest">
	<em:id>ublock0-updater@Off.JustOff</em:id>
	<em:version>1.1.0</em:version>
	<em:type>2</em:type>
	<em:bootstrap>true</em:bootstrap>
	<em:name>uBlock Origin Updater</em:name>
	<em:description>Keep uBlock Origin up to date using the latest release from GitHub</em:description>
	<em:creator>Off JustOff &lt;Off.Just.Off@gmail.com&gt;</em:creator>
	<em:homepageURL>https://github.com/JustOff/ublock0-updater/</em:homepageURL>
	<em:targetApplication>
	  <Description>
		<em:id>{8de7fcbb-c55c-4fbe-bfc5-fc555c87dbc4}</em:id>
		<em:minVersion>27.0.0</em:minVersion>
		<em:maxVersion>27.*</em:maxVersion>
	  </Description>
	</em:targetApplication>
  </Description>
</RDF>
```
As a result, v1.1.0 can't be installed in Firefox; FWIW, install.rdf should have been like [this](https://raw.githubusercontent.com/JustOff/ublock0-updater/c2544df9824cf4f48425bcae66bd242600c86667/install.rdf); for the same reason, uploaded v1.1.0 won't install in SeaMonkey too; kindly re-upload proper versions....

Thanks

**Comment by JustOff** [comment]
> it appears that the .XPI file of version 1.1.0 uploaded to APO as well as GitHub has a faulty install.rdf

Thanks for reporting this. Actually, since APO serves only Pale Moon, all is ok there. The proper 1.1.0 is on GitHub now.

> can you please clarify whether it was indeed impossible to cover those earlier Fx versions or whether in fact code adaptation would've allowed for that but you opted not to

Sorry, but I just don't feel reasonable to support completely outdated versions. Feel free to modify it for your needs locally.
