### ISSUE TITLE
Provide the possibility of the initial installation of uB0 directly from Updater

### ISSUE THREAD

**Issue by JustOff** [JustOff/ublock0-updater#11]
Since XUL-compatible versions of uB0 have been moved to a separate branch and will not be always updated in sync with the versions based on WebExtensions, it may be hard to find the required package for the initial installation among the list of all releases.

Thus, it would be useful to provide the possibility of initial installation of uB0 directly from uB0 Updater.

**Comment by mk-pmb** [comment]
:+1: I'd appreciate that.
