### ISSUE TITLE
Question about uBlock Origin

### ISSUE THREAD

**Issue by blahdiblah** [JustOff/ublock0-updater#117]
Does this mean the ublock team have started to include legacy browsers in their version scheme? I'd got the idea it was an alternate team that was looking after that branch. Alternately has someone outside the main ublock crew (Heroes either way!) tweaked the code and created an alternately managed branch?  Edit - Sorry for mixed up fields - never guess I'm not habitual git-hubber wouldya :)

**Comment by JustOff** [comment]
No, the version scheme remains the same and is unlikely to change until all the functionality is consistent with the mainline version. As far as I can, I try to participate in improving uBO for legacy-based browsers, and I hope that more developers will join this effort.
