### ISSUE TITLE
v1.6.2 doesn't pick up uBlock0-legacy-1.16.4.1 on Firefox ESR 52.8.1

### ISSUE THREAD

**Issue by Vangelis66** [JustOff/ublock0-updater#14]
Hello 😄 

OS: Windows Vista SP2 32-bit
Mozilla Firefox ESR **52.8.1** (32-bit)
uBlock Origin Updater **1.6.2** (updated from 1.6.1, followed by a browser restart, just to be sure... ) 
NB: In its settings, I have checked the option: 
"**Include Beta versions**" 
(just a thought, but perhaps this setting should go now, as per https://github.com/JustOff/ublock0-updater/pull/13 ?)
uBlock Origin v**1.16.4** (**legacy**)

When I manually check in AOM for updates, 
I am not offered the update to [legacy-1.16.4.1](https://github.com/gorhill/uBlock/releases/tag/firefox-legacy-1.16.4.1) 😞 👎 
(tested the same on non-ESR Fx 52.0.2 & 53.0.3... )

On that same laptop, in the case of Pale Moon **27.9.2** (32-bit) with the same version combination of uBlock0 updater (1.6.2) and uBlock0-legacy (1.16.4), uBlock0-legacy-1.16.4.1 was successfully picked up from the GitHub repo and installed... 

I think I have provided all needed info, feel free to request anything additional 
required towards the resolution of this issue 😉 

Many thanks for this extension, supporting the XUL flavour of uBlock0 on my browsers of choice...
Regards

**Comment by JustOff** [comment]
Resolved by [1.6.3](https://github.com/JustOff/ublock0-updater/releases/tag/1.6.3).
