### ISSUE TITLE
An updater for Nano Adblocker

### ISSUE THREAD

**Issue by joshcangit** [JustOff/ublock0-updater#15]
I hope to have an updater for Nano Adblocker and Nano Defender.
The creator of uBlock Protector on Github, jspenguin2017, rename the project to Nano Defender and made Nano Adblocker, forked from uBlock Origin, to work with Nano Defender. The creator of both add-ons is unable to get them onto AMO so Firefox will not update them and newer versions do not overwrite older versions that were installed. Another Github user is helping to host releases for both add-ons. An updater would be of great help.

**Comment by JustOff** [comment]
Sorry, but I'm not interested.
