### ISSUE TITLE
How to install this updater into our legacy web browsers?

### ISSUE THREAD

**Issue by antdude** [JustOff/ublock0-updater#16]
I don't see a XPI file to install its extension for my SeaMonkey v2.49.4 web browsers. Sorry to ask a newbie question. :(

**Comment by JustOff** [comment]
See the [Releases](https://github.com/JustOff/ublock0-updater/releases) section.

**Comment by antdude** [comment]
Thanks. Where is that linked on https://github.com/JustOff/ublock0-updater ? I don't see it.

**Comment by antdude** [comment]
Thanks. :)

**Comment by mk-pmb** [comment]
The links are totally unclear. I'd have expected them to point to the websites of each browser.
