### ISSUE TITLE
Update uBO to 1.17

### ISSUE THREAD

**Issue by Symbian9** [JustOff/ublock0-updater#17]
New uBO released:

- https://github.com/gorhill/uBlock/releases/tag/1.17.0

But I still don't got an auto-update. Why? How fix it?

![addons list](http://i.imgur.com/EIBl5FF.png)

**Comment by Vangelis66** [comment]
uB0 v**1.17.0** is of the **WebExtension** format, as such is **not supported** in Pale Moon and not picked up by uB0 updater; only the XUL (**firefox-legacy**) format is supported, as you can see in [tags](https://github.com/gorhill/uBlock/tags), the latest version (1.16.4.4) is already installed in your copy of the browser! 

Please close this issue as **INVALID**...
