### ISSUE TITLE
v1.6.4 doesn't pick up uBlock0-legacy-1.16.4.6

### ISSUE THREAD

**Issue by Vangelis66** [JustOff/ublock0-updater#18]
Hello 😄 

I have the latest (**1.6.4**) version of this extension installed in several "legacy" browsers (Pale Moon 27.9.4/Tycho, Firefox 52.0.2, Firefox 53.0.3, Cyberfox 52.9.1, FirefoxESR 52.9.0, "unbranded" fork of Pale Moon 28/UXP - all of them in portable installations 😉 ) in my Windows Vista SP2 32-bit laptop, together with the "legacy" flavour of uBlock0 v**1.6.4.5**; when checking for add-on updates manually, nothing related to uB0 shows up 😕 ... 
_However_, according to the GitHub repo of uB0, new "legacy" version **1.6.4.6** has been released over eleven hours ago (at this time of posting): 

https://github.com/gorhill/uBlock/releases/tag/firefox-legacy-1.16.4.6

Why aren't I being offered this update via **ublock0-updater**? Please advise... 
Thanks in advance for any action taken to rectify this issue... 

Kind regards

**Comment by JustOff** [comment]
Resolved by [uB0 1.6.5](https://github.com/JustOff/ublock0-updater/releases/tag/1.6.5), thanks for reporting this.

**Comment by Vangelis66** [comment]
> Resolved by uB0[**-updater**]-1.6.5, thanks for reporting this.

... You are very welcome! 😃 Congrats for the swift fix 👍
