### ISSUE TITLE
Have GitHub broken the extension once more?

### ISSUE THREAD

**Issue by Vangelis66** [JustOff/ublock0-updater#19]
Greetings from Greece :smiley: 

I keep several older versions of (non-Quantum) **Firefox** (portable **PAF** installations) in my old (Vista SP2 32-bit) laptop, for archival and testing purposes; still in that same laptop, a **Pale Moon 27.9.4**/Tycho installation, as the default browser; all these browser profiles have **uBlock0-legacy** as content blocker, **ublock0-updater** (this extension) v**1.6.7/1.6.8b1** installed and add-ons are configured to be manually checked for updates.

On the evening of Mon, Dec 16th, I was notified of the available update (from 1.16.4.11) to **1.16.4.12** and I successfully updated to it in both the **PM27**+one **FxESR 52.9.1** profiles...

Some hours ago, I booted again the Vista laptop, wanting to update **uBlock0-legacy** in the rest of the browser profiles; all had still v**1.16.4.11**, some had **ublock0-updater v1.6.7** (latest stable release), but most had the beta, v**1.6.8b1**; imagine my surprise when I found out that in none of those, yet "un-updated", browser profiles I was offered v**1.16.4.12** to upgrade to... :angry: 

I thought I was going mad, but applied several troubleshooting actions, among which: reboot the machine, get a new IP address from router, change IP address' country via VPN, clear browser cookies and cache, restart browsers several times, **all to no avail**! 

In another test, I downgraded **uBlock0-legacy** v**1.16.4.12** (updated last Monday) to v**1.16.4.11** in my **Tycho** profile and with **ublock0-updater v1.6.8b1** (which had worked on Monday) _I failed to update back to_ v**1.16.4.12**: 

![PM27](https://user-images.githubusercontent.com/9669492/71052626-93458e00-2154-11ea-8647-7abb58f3c0fd.JPG)

Same situation with a **FxESR 52.9.0** profile (the one I am posting with...), which gets stuck in v**1.16.4.11**: 

![FxESR52](https://user-images.githubusercontent.com/9669492/71052763-11a23000-2155-11ea-8ca9-96b59be324be.JPG)

Unless it's something local in my setup that eludes me, this, to me, looks like another GitHub related breakage (but I could be wrong, of course...); can you please investigate?

Many thanks indeed for maintaining this extension and for being actively involved in keeping the "legacy" version of uB0 around... :+1: 

Best regards :smile:

**Comment by JustOff** [comment]
Thanks for reporting the issue, it has been addressed in [1.6.8](https://github.com/JustOff/ublock0-updater/releases/tag/1.6.8).
