### ISSUE TITLE
umatrix

### ISSUE THREAD

**Issue by gv01** [JustOff/ublock0-updater#2]
Hi!

Can you do a similar extension for uMatrix (replacing ublock with umatrix is trivial - it's seems to work fine for me locally)?

Thank you.

**Comment by JustOff** [comment]
Ok, but I'm rather going to integrate uMatrix support right into uB0 Updater.

**Comment by gv01** [comment]
That's even better. Thank you.

**Comment by JustOff** [comment]
Resolved by [1.2.0](https://github.com/JustOff/ublock0-updater/releases/tag/1.2.0).
