### ISSUE TITLE
Please add Imagus support

### ISSUE THREAD

**Issue by pintassilgo** [JustOff/ublock0-updater#3]
Another extension converted to WebExtensions that stills updates legacy version.

WebExtensions: https://addons.mozilla.org/en-US/firefox/addon/imagus/
Legacy: https://drive.google.com/drive/folders/0Bx8fnUCX4W2IVDdReXo3Mjhxc00

(Just for curiosity, Imagus dev - Deathamns - is the one that ported uBO to Firefox)

**Comment by JustOff** [comment]
Someone else should create a separate add-on for this.
