### ISSUE TITLE
Dynamic filtering pane scrollbar glitch in popup panel

### ISSUE THREAD

**Issue by gorhill** [JustOff/ublock0-updater#5]
Latest versions of Pale Moon are afflicted by this issue (well, on my side, with default installation of Pale Moon): https://github.com/gorhill/uBlock/issues/108

This needs to be fixed in Pale Moon, but meanwhile I am trying to figure out a temporary hack for users of uBO on Pale Moon. The following CSS rule should make the dynamic filter pane more usable, this moves the scrollbar to the right:

    #uBO-popup-panel body #panes > div:nth-of-type(2) {
        direction: ltr;
    }

However I am a total illiterate when it comes to tamper with browser styles. I created a `userChrome.css` file in my profile and added the above rule, and this had no effect after restating the browser.

Anyway, my point is that I would like whatever trick works to temporarily fix this browser issue to be shared with users of uBO on Pale Moon -- if you know how to make the above style apply to uBO's popup panel without having to change uBO itself.

Here is a URL where the issue manifest, because the list of 3rd parties is long enough:
`https://www.economist.com/blogs/buttonwood/2017/11/greater-fool-theory-0`

**Edit:** when I say "shared", I just mean informing Pale Moon users on Pale Moon's forum. But I am blocked on how to make the hack work, so really I am just asking for assistance.

**Comment by JustOff** [comment]
It seems this style requires `!important` keyword.

I can add a [workaround](https://github.com/JustOff/ublock0-updater/commit/45fcb866ccb33f1182a9ef65725e6da182c090fc) to my Updater, but not every uBlock user uses it.

**Comment by gorhill** [comment]
Of course best would be it's fixed in Pale Moon (paging @wolfbeast).

**Comment by gorhill** [comment]
Ok so anyway, I finally found how to have user styles applied:

- Go into profile folder.
- From there, go into `chrome` folder.
    - Create it if it does not exist.
- Open `userContent.css`.
    - Create it if it does not exists.
- Add following CSS rule in the text file:
  ```
  #uBO-popup-panel body #panes > div:nth-of-type(2) {
    direction: ltr !important;
  }
  ```
- Save.
- Restart Pale Moon.

Eventually this can be removed when the issue is fixed in Pale Moon.

So anyway, this is what I wanted to know, how to add user styles. The comment can now be used as reference solution in case someone reports suffering the issue.

**Comment by JustOff** [comment]
@gorhill, actually I'm not sure it's Pale Moon problem, 'cause I see exactly the same rtl layout issue in Firefox 56.0.2 & uBlock Origin 1.14.8: 
![firefox_2017-11-09_20-02-57](https://user-images.githubusercontent.com/340855/32621813-a90d0afc-c589-11e7-8f5f-4476b9caa186.png)

**Comment by gorhill** [comment]
I don't see an issue in your screenshot.

**Comment by JustOff** [comment]
Hm... then I probably don't understand what is the problem with Pale Moon, here is how it looks for me:
![palemoon_2017-11-09_20-14-16](https://user-images.githubusercontent.com/340855/32622199-d0418c46-c58a-11e7-9b3e-fd313942fa08.png)

**Comment by gorhill** [comment]
What version of Pale Moon is this? I had the issue with 27.5.0 and also with the new 27.6.0. Linux version:

![a](https://user-images.githubusercontent.com/585534/32622759-f51ec472-c551-11e7-9756-240f2a3e17f7.png)

**Comment by JustOff** [comment]
> What version of Pale Moon is this?

27.6.0 x86 @ Win7 x64, I also tried 27.5.1 and 27.7.0a1 and don't see the issue like on your screenshot.

I'm going to check on linux (ubuntu & mint) and post an update.

**Comment by JustOff** [comment]
But `layers.async-pan-zoom.enabled` is `false` by default in Pale Moon, moreover Pale Moon doesn't support e10s at all, so I'm not sure is there are any issue here.

**Comment by gorhill** [comment]
> so I'm not sure is there are any issue here.

I guess there are none. I have no clue why this was set to `true` on my side, I use a portable version of Pale Moon. Sorry for the noise.

**Comment by JustOff** [comment]
Nonetheless, I thank you for paying attention to support Pale Moon, feel free to contact me on this case in any time!

**Comment by wolfbeast** [comment]
APZ has a few known tiling issues, it's disabled for that reason ;)
Anyway, glad you figured it out! De-CCing myself from this issue.
