### ISSUE TITLE
Error updating uMatrix Beta due to no latest uMatrix.firefox.xpi

### ISSUE THREAD

**Issue by kowith337** [JustOff/ublock0-updater#6]
The latest version of uMatrix Legacy is [1.1.4](https://github.com/gorhill/uMatrix/releases/1.1.4).

In fact, the current latest version is [1.1.6](https://github.com/gorhill/uMatrix/releases/1.1.6) _(but it doesn't have `umatrix.firefox.xpi`, also)_

And now seems like no future update for legacy version anymore...

**Comment by JustOff** [comment]
Thanks, [I'm aware of this](https://forum.palemoon.org/viewtopic.php?p=127779#p127779), it's going to be removed from the Updater as well.

**Comment by JustOff** [comment]
Resolved by [1.3.0](https://github.com/JustOff/ublock0-updater/releases/tag/1.3.0).
