### ISSUE TITLE
uB0 auto-updates to the webextension version on Waterfox now

### ISSUE THREAD

**Issue by Mofozilla512** [JustOff/ublock0-updater#9]
I use the legacy uB0 on Waterfox because the webextension version is castrated (unable to block things on AMO or about: pages for example) and broken (because of webextension storage bugs like https://bugzilla.mozilla.org/show_bug.cgi?id=1313401).

ublock0-updater worked well until recently. But now the legacy uB0 auto-updated to the webext uB0 1.15.0 . I uninstalled this uB0 and installed the legacy uB0 1.15.0 instead from github. Today again, it auto-updated to the webext 1.15.4 . Note that when it does so, settings from the legacy uB0 are not transfered to the webext uB0.

I'm using Waterfox 56.0.4.1 64bits on windows 7 64bits, and ublock0-updater 1.3.0.

**Comment by JustOff** [comment]
Resolved by [1.3.1](https://github.com/JustOff/ublock0-updater/releases/tag/1.3.1).

**Comment by Vangelis66** [comment]
FWIW, this should be the same underlying issue I first reported last October [here](https://github.com/JustOff/ublock0-updater/issues/4#issuecomment-338344356), albeit in the wrong place... 
**Not Waterfox** back then (I'm on a 32-bit OS), but **Firefox versions 52.x.x to 56.x.x**, eligible for both the XUL & WebExt versions of uBO; like the OP here, I do prefer the XUL over the WebExt version, when such a choice is available 😃 ... 

Thank you for the fix in **ublock0-updater 1.3.1** (_Improved background update interception_):+1:; hopefully, the webextension uBO version won't be inadvertently installed in the future... 

Best regards

**Comment by JustOff** [comment]
Yeah, you're right, it certainly was my fault. Somehow I missed that all browsers except Pale Moon use an additional address for background updates :flushed:
